---
title: "data_merging"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{data_merging}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

```{r setup}
library(EcoCleanR)
```

#Background

In this tutorial we will show merging occurrence records of an example species from various online biodiversity aggregates. e.g. gbif, obis, idigbio and invertEBase

#Code execution:
```{r libraries}
#Install packages
library(rgbif)
library(ridigbio)
library(robis)
#library(rSymbiota)
#install.packages("devtools")
#devtools::install_github("FranzKrah/rSymbiota")
library(dplyr)
# select species of interest
species_name <- "Mexacanthina lugubris"
taxonkey <- name_backbone(species_name)$usageKey
## attribute list has required fields of interest following DwG standards
attribute_list <- c("source", "catalogNumber", "basisOfRecord", "occurrenceStatus", "institutionCode", "verbatimEventDate", "scientificName", "individualCount", "organismQuantity", "abundance", "decimalLatitude", "decimalLongitude", "coordinateUncertaintyInMeters", "locality", "verbatimLocality", "municipality", "county", "stateProvince", "country", "countryCode")

# GBIF - data extraction and standardization---------
gbif.occ <- occ_data(taxonKey = taxonkey, occurrenceStatus = NULL, limit = 10000L)$data
## we are making one column called abundance which should have values from individual count and organism Quantity
gbif.occ$abundance <- ifelse(is.na(as.numeric(gbif.occ$individualCount)), as.numeric(gbif.occ$organismQuantity), as.numeric(gbif.occ$individualCount))
## additional field added to know the source
gbif.occ$source <- "gbif"
gbif.occ_temp <- gbif.occ[, attribute_list]
str(gbif.occ_temp[,1:3])
## end of GBIF data extraction

# OBIS- data extraction and standardization---------
obis.occ <- occurrence(species_name)
for (field in attribute_list) {
  if (!field %in% names(obis.occ)) {
    obis.occ[[field]] <- NA # Add the missing field as NA
  }
}
obis.occ$abundance <- ifelse(is.na(as.numeric(obis.occ$individualCount)), as.numeric(obis.occ$organismQuantity), as.numeric(obis.occ$individualCount))
obis.occ$source <- "obis"
obis.occ$municipality <- ""
obis.occ_temp <- obis.occ[, attribute_list]
str(obis.occ_temp[,1:3])

## end of OBIS data extraction

# IDIGBIO - data extraction and standardization---------
idig.occ <- idig_search_records(
  type = "records",
  rq = list("scientificname" = species_name),
  field = "all",
  max_items = 10000L,
  limit = 10000L,
  offset = 0
)

idig.occ <- idig.occ %>%
  mutate(
    abundance = as.numeric(individualcount),
    source = "idigbio",
    occurrenceStatus = "",
    organismQuantity = ""
  ) %>%
  rename(
    decimalLatitude = geopoint.lat,
    decimalLongitude = geopoint.lon,
    basisOfRecord = basisofrecord,
    catalogNumber = catalognumber,
    scientificName = scientificname,
    stateProvince = stateprovince,
    coordinateUncertaintyInMeters = coordinateuncertainty,
    individualCount = individualcount,
    institutionCode = institutioncode,
    verbatimLocality = verbatimlocality,
    verbatimEventDate = verbatimeventdate,
    countryCode = countrycode
  )

idig.occ_temp <- idig.occ[, attribute_list]
str(idig.occ_temp[,1:3])

##end of idigbio data extraction

#InvertEbase - data extraction and standardization---------
###rSymbiota is utilize for invertEBase which required addition soft loading called - docker to run ther server. We are not running this code due to system dependency

###mycoportal <- "http://invertebase.org/portal/index.php"
###sym.occ <- symbiota(taxon = "mexacanthina lugubris", db = mycoportal)

#Instead we will use csv file downloaded from invertEBase, please use this file as template
sym.occ <- example_sp_invertebase
sym.occ$abundance <- as.numeric(sym.occ$individualCount)

for (field in attribute_list) {
  if (!field %in% names(sym.occ)) {
    obis.occ[[field]] <- NA  # Add the missing field as NA
  }
}

str(sym.occ[,1:3])
### end of InvertEBase 

#Merging the databases
Mixdb.occ <- ec_db_merge(datatype = "modern", gbif.occ_temp, obis.occ_temp, idig.occ_temp, sym.occ)

str(Mixdb.occ[,1:3])
#end of merge data. Note - we have duplicates which will be removed as part of data cleaning file.

```


